server:
  port: 8087
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/firecontrol?useUnicode=true&characterEncoding=utf-8&userSSL=false&serverTimezone=UTC
    username: root
    password: superff
    driver-class-name: com.mysql.cj.jdbc.Driver
    minIdle: 5
    maxActive: 100
    initialSize: 10
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 50
    removeAbandoned: true
    filters: stat # ,wall,log4j # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000 # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    useGlobalDataSourceStat: true # 合并多个DruidDataSource的监控数据
    druidLoginName: wjf # 登录druid的账号
    druidPassword: wjf # 登录druid的密码
    cachePrepStmts: true # 开启二级缓存

  jackson:
    time-zone:  GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

  rabbitmq:
    host: 106.12.72.100
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true #确认消息已经到达交换机
    publisher-returns: true #确认消息已经发送到队列


mybatis:
   mapperLocations: classpath:/mapper/*.xml
#   别名
   typeAliasesPackage: com.orient.firecontrol_server_demo.model
#   包扫描
   mapperScanPackage: com.orient.firecontrol_server_demo.dao


logging:
  level:
    com.orient.firecontrol_server_demo: debug #com.orient.server包下所有class以debug级别输出 控制台打印sql语句（debug级别才可以）



